### ISSUE TITLE
Role of Tanstack Start here ?

### ISSUE THREAD

**Issue by sohamnandi77** [crstnmac/tanstack-start-hono-drizzle-template#1]
Hi @crstnmac, I'm exploring TanStack Start and I see that it supports API routes, server functions, and other backend features. So it's fully capable to make a fullstack framework, it uses nitro which internally uses h3 for route matching and routing. I get it, we want to use Hono.js as my backend framework for routing and handling server-side logic.

I am not getting, How does TanStack Start fit into this configuration? Will TanStack Start act as a front-end-only framework in this case, or does it also help manage the API routes handled by Hono? can you please clarify the role of Tanstack Start here ?

Thanks, BTW great template. 🙌

**Comment by crstnmac** [comment]
There is no role of tanstack-start here, im using tanstack router and hono as backend api routes

**Comment by sohamnandi77** [comment]
Oh, I see! I thought `@tanstack/start` was listed under the frontend dependencies, so I was just curious about it.
